services:
  backend:
    image: hasanpulikkal/backend-web:latest
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate --fake-initial &&
        python manage.py collectstatic --noinput &&
        daphne -b 0.0.0.0 -p 8000 backend.asgi:application
      "
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: always

  celery-worker:
    image: hasanpulikkal/backend-web:latest
    command: celery -A backend worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - backend
      - redis
    restart: always

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  static_volume: