# Generated by Django 5.1.5 on 2025-03-11 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_workers',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker'),
        ),
    ]
