# Generated by Django 5.1.5 on 2025-02-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_google_id_customuser_profile_picture_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_login',
            field=models.BooleanField(default=False),
        ),
    ]
