# Generated by Django 5.1.5 on 2025-03-11 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('full_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=2)),
                ('experience', models.CharField(max_length=2)),
                ('previous_company', models.CharField(blank=True, max_length=16, null=True)),
                ('salary', models.CharField(max_length=4)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('description', models.TextField()),
                ('qualification', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_prof', models.ImageField(blank=True, null=True, upload_to='id_profes/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('total_fee', models.FloatField(default=0.0)),
                ('payed_fee', models.FloatField(default=0.0)),
                ('pending_fee', models.FloatField(default=0.0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='worker', to='worker.jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerAvailability',
            fields=[
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='worker.worker')),
            ],
            options={
                'unique_together': {('worker', 'day_of_week', 'start_time')},
            },
        ),
    ]
