# Generated by Django 5.1.5 on 2025-02-03 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('age', models.CharField(max_length=2)),
                ('salary', models.CharField(max_length=4)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('description', models.TextField()),
                ('qualification', models.TextField()),
                ('experience', models.CharField(max_length=2)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_prof', models.ImageField(upload_to='id_profes/')),
                ('full_name', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('job', models.CharField(max_length=16)),
                ('previous_company', models.CharField(blank=True, max_length=16, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
