# Generated by Django 5.1.5 on 2025-02-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_worker_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id_prof',
            field=models.ImageField(blank=True, null=True, upload_to='id_profes/'),
        ),
    ]
