# Generated by Django 5.1.5 on 2025-02-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_alter_worker_id_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='latitude',
            field=models.FloatField(default=11.1483267),
        ),
        migrations.AddField(
            model_name='worker',
            name='longitude',
            field=models.FloatField(default=75.8925958),
        ),
    ]
