# Generated by Django 5.1.5 on 2025-02-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_worker_latitude_worker_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
