# Generated by Django 5.1.5 on 2025-02-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_alter_worker_latitude_alter_worker_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
