# Generated by Django 5.1.5 on 2025-02-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_worker_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
