# Generated by Django 5.1.5 on 2025-02-07 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0009_worker_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='worker', to='worker.jobs'),
        ),
    ]
