# Generated by Django 5.1.5 on 2025-02-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0010_alter_worker_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
