# Generated by Django 5.1.5 on 2025-02-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0012_workeravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='workeravailability',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
