# Generated by Django 5.1.5 on 2025-02-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0013_workeravailability_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workeravailability',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
