# Generated by Django 5.1.5 on 2025-02-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0014_alter_workeravailability_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='payed_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='worker',
            name='pending_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='worker',
            name='total_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
