# Generated by Django 5.1.5 on 2025-02-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0015_worker_payed_fee_worker_pending_fee_worker_total_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='payed_fee',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='pending_fee',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='total_fee',
        ),
    ]
