# Generated by Django 5.1.5 on 2025-02-27 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0017_worker_payed_fee_worker_pending_fee_worker_total_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('pyment_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('credit', 'Amount Creat'), ('debit', 'Amount debit')], default='credit', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='worker.worker')),
            ],
        ),
    ]
