# Generated by Django 5.1.5 on 2025-03-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('pyment_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('credit', 'Amount Credit'), ('debit', 'Amount Debit')], default='credit', max_length=10)),
            ],
        ),
    ]
