# Generated by Django 5.1.5 on 2025-03-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=50)),
                ('any_previous_issues', models.TextField()),
                ('damaged_parts', models.TextField()),
                ('details', models.TextField()),
                ('booked_date', models.DateField(blank=True, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('booking_time', models.TimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='booking_photos/')),
                ('total', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('created', 'Booking Created'), ('accepted', 'Labor Accepted'), ('canceled', 'User Canceled'), ('rejected', 'Labor Rejected'), ('pending', 'Work Pending'), ('completed', 'Completed'), ('visited', 'Place Visited'), ('liked', 'User Like')], default='created', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(0.5, '0.5'), (1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3'), (3.5, '3.5'), (4, '4'), (4.5, '4.5'), (5, '5')], decimal_places=1, default=5, max_digits=2)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
