# Generated by Django 5.1.5 on 2025-02-17 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0014_alter_workeravailability_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField(default='01:00:00')),
                ('any_previous_issues', models.TextField()),
                ('damaged_parts', models.TextField()),
                ('details', models.TextField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'Booking Created'), ('accepted', 'Labor Accepted'), ('rejected', 'Rejected'), ('pending', 'Work Pending'), ('completed', 'Completed'), ('visited', 'Place Visited'), ('liked', 'User Like')], default='created', max_length=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='worker.jobs')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='booking', to='worker.workeravailability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='worker.worker')),
            ],
        ),
    ]
