# Generated by Django 5.1.5 on 2025-02-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_time',
            new_name='booking_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
