# Generated by Django 5.1.5 on 2025-02-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_booked_time_booking_booking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='booking_photos/'),
        ),
    ]
