# Generated by Django 5.1.5 on 2025-02-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
